#heroku addons:attach heroku-postgresql -a <app_name> --as HEROKU_DATABASE
#heroku addons:detach DATABASE -a <app_name>

# heroku addons:attach heroku-postgresql -a weathe-iada --as HEROKU_DATABASE
# heroku addons:detach DATABASE -a weathe-iada

# heroku config:add DATABASE_URL=mysql2://norton:nortonbixinha@137.184.18.216:3306/norton
# heroku config:add SHARED_DATABASE_URL=mysql2://norton:nortonbixinha@137.184.18.216:3306/norton
# heroku restart
# git push heroku main

#heroku logs --tail
#  heroku addons:create heroku-redis:hobby-dev -a weathe-iada
# heroku ps:scale web=1
# heroku ps:scale worker+1
# url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
# bundle exec rake assets:precompile



#  heroku run bash -a APPNAME
#  $ cd app
 
default: &default
  adapter:  mysql2
  encoding: utf8
  host:     137.184.18.216
  database: norton
  port:     3306
  username: norton
  password: 'nortonbixinha'

development:
  <<: *default


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

#test:
#  adapter: postgresql
#  encoding: unicode
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  database: weathe_iada_test
