default: &default
  adapter:  mysql2
  encoding: utf8
  host:     137.184.18.216
  database: norton
  port:     3306
  username: norton
  password: 'nortonbixinha'

development:
  <<: *default


production:
  <<: *default

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: weathe_iada_test


