class ImportDatum < ApplicationRecord
  # main config ...............................................................
  self.table_name = "tb_import_data"
  self.sequence_name = "tb_import_data_seq"
  # relationships .............................................................
  belongs_to :import, class_name: 'Import', foreign_key: :tb_import_id
  # validations ...............................................................
  # callbacks .................................................................
end
