class Import < ApplicationRecord
  # main config ...............................................................
  self.table_name = "tb_import"
  self.sequence_name = "tb_import_seq"
  # relationships .............................................................
  has_many :import_datas, class_name: 'ImportDatum', foreign_key: :tb_import_id
  # validations ...............................................................
  validates :cdg_import, uniqueness: true, presence: true
  # callbacks .................................................................
end
